[package]
name = "app"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { version = "0.1.8", features = ["desktop"] }
todo_core = { path = "../core" }
crossbeam-channel = "0.5"

